// Lista base de cartas de conceptos opuestos
const CARDS = [
  { left: "Frío", right: "Caliente" },
  { left: "Inútil en un apocalipsis zombi", right: "Muy útil en un apocalipsis zombi" },
  { left: "Mal trabajo", right: "Buen trabajo" },
  { left: "Infravalorado", right: "Sobrevalorado" },
  { left: "Fácil de aprender", right: "Difícil de aprender" },
  { left: "Comida de diario", right: "Comida de lujo" },
  { left: "Película mala", right: "Obra maestra del cine" },
  { left: "Superpoder inútil", right: "Superpoder increíble" },
  { left: "Plan tranquilo", right: "Fiesta salvaje" },
  { left: "Personaje histórico villano", right: "Personaje histórico heroico" },
  { left: "Canción para llorar", right: "Canción para motivarse" },
  { left: "Lugar incómodo", right: "Lugar muy cómodo" },
  { left: "Hobby barato", right: "Hobby carísimo" },
  { left: "Regalo decepcionante", right: "El mejor regalo posible" },
  { left: "Moda pasajera tonta", right: "Tendencia atemporal" },
  { left: "Talento inútil", right: "Habilidad muy útil en la vida" },
  { left: "Animal aterrador", right: "Animal monísimo" },
  { left: "Comida sobrevalorada", right: "Comida infravalorada" },
  { left: "Sabor dulce", right: "Sabor salado" },
  { left: "Día normal en clase", right: "Caos absoluto" },
  { left: "Famoso odiado", right: "Famoso amado" },
  { left: "Mala mano de mus", right: "Buena mano de mus" },
  { left: "Futbolista horroroso", right: "Futbolista top mundial" },
  { left: "Cosa de gitanos", right: "Cosas de payos" },
  { left: "Marca barata", right: "Marca cara" },
  { left: "Mal sitio de previa", right: "Buen sitio de previa" },
];