// Lista base de cartas de conceptos opuestos
const CARDS = [
  { left: "Frío", right: "Caliente" },
  { left: "Inútil en un apocalipsis zombi", right: "Muy útil en un apocalipsis zombi" },
  { left: "Mal trabajo", right: "Buen trabajo" },
  { left: "Infravalorado", right: "Sobrevalorado" },
  { left: "Fácil de aprender", right: "Difícil de aprender" },
  { left: "Comida de diario", right: "Comida de lujo" },
  { left: "Película mala", right: "Obra maestra del cine" },
  { left: "Superpoder inútil", right: "Superpoder increíble" },
  { left: "Plan tranquilo", right: "Fiesta salvaje" },
  { left: "Personaje histórico villano", right: "Personaje histórico heroico" },
  { left: "Canción para llorar", right: "Canción para motivarse" },
  { left: "Lugar incómodo", right: "Lugar muy cómodo" },
  { left: "Hobby barato", right: "Hobby carísimo" },
  { left: "Regalo decepcionante", right: "El mejor regalo posible" },
  { left: "Moda pasajera tonta", right: "Tendencia atemporal" },
  { left: "Talento inútil", right: "Habilidad muy útil en la vida" },
  { left: "Animal aterrador", right: "Animal monísimo" },
  { left: "Comida sobrevalorada", right: "Comida infravalorada" },
  { left: "Sabor dulce", right: "Sabor salado" },
  { left: "Día normal en clase", right: "Caos absoluto" },
  { left: "Famoso odiado", right: "Famoso amado" },
  { left: "Mala mano de mus", right: "Buena mano de mus" },
  { left: "Futbolista horroroso", right: "Futbolista top mundial" },
  { left: "Cosas de gitanos", right: "Cosas de payos" },
  { left: "Cosas de negros", right: "Cosas de blancos" },
  { left: "Cosas de tías", right: "Cosas de tíos" },
  { left: "Cosas de izquierdas", right: "Cosas de derechas" },
  { left: "Homosexual", right: "Heterosexual" },
  { left: "Marca barata", right: "Marca cara" },
  { left: "Mal sitio de previa", right: "Buen sitio de previa" },
  { left: "Mala hora para irse de fiesta", right: "Buena hora para irse de fiesta" },
  { left: "Mala ciudad de España", right: "Buena ciudad de España" },
  { left: "No debería haber salido", right: "Temazo" },
  { left: "Mal número de personas para salir", right: "Buen número de personas para salir" },
  { left: "No cuernos", right: "Cuernos" },
  { left: "Ogro", right: "Queso" },
  { left: "Mala mano de póker", right: "Buena mano de póker" },
  { left: "Choni", right: "Pija" },
  { left: "Mal tamaño", right: "Buen tamaño" },
  { left: "Mala frase para despedirse", right: "Buena frase para despedirse" },
  { left: "Mala frase para ligar", right: "Buena frase para ligar" },
  { left: "Palabra normal", right: "Panchitada top" },
  { left: "Mala frase para cortar", right: "Buena frase para cortar" },
  { left: "Rata", right: "Pagafantas" },
  { left: "Mal mote", right: "Buen mote" },
  { left: "Mala fecha de cumpleaños", right: "Buena fecha de cumpleaños" },
];